/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://36kvkqs4hfclvn2mmiy43qnbbu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5qtakrggjvdh7o42pgjssncnv4",
    "aws_cognito_identity_pool_id": "us-east-1:140e982d-1d9f-41e8-8f01-9f7848ae64f1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_75otdWoE5",
    "aws_user_pools_web_client_id": "1s0kr8ddme31aqstjfvpcal57m",
    "oauth": {
        "domain": "gy9fkrafvsj0-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "com.joey123ms.ubereatsuser://signInRedirect",
        "redirectSignOut": "com.joey123ms.ubereatsuser://signOutRedirect",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "uber-eats-bucket142552-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
